export const GET_LOADS_REQUEST = 'GET_LOADS_REQUEST';
export const GET_LOADS_SUCCESS = 'GET_LOADS_SUCCESS';

export const ADD_LOAD_REQUEST = 'ADD_LOAD_REQUEST';

export const GET_ACTIVE_LOADS_REQUEST = 'GET_ACTIVE_LOADS_REQUEST';
export const GET_ACTIVE_LOADS_SUCCESS = 'GET_ACTIVE_LOADS_SUCCESS';

export const ITERATE_TO_NEXT_STATE_REQUEST = 'ITERATE_TO_NEXT_STATE_REQUEST';
