export const GET_LOADS_REQUEST = 'GET_LOADS_REQUEST';
export const GET_LOADS_SUCCESS = 'GET_LOADS_SUCCESS';

export const ADD_LOAD_REQUEST = 'ADD_LOAD_REQUEST';

export const EDIT_LOAD_REQUEST = 'EDIT_LOAD_REQUEST';

export const DELETE_LOAD_REQUEST = 'DELETE_LOAD_REQUEST';
export const DELETE_LOAD_SUCCESS = 'DELETE_LOAD_SUCCESS';

export const POST_LOAD_REQUEST = 'POST_LOAD_REQUEST';

export const GET_SHIPP_INFO_REQUEST = 'GET_SHIPP_INFO_REQUEST';
export const GET_SHIPP_INFO_SUCCESS = 'GET_SHIPP_INFO_SUCCESS';

export const GET_ACTIVE_LOADS_REQUEST = 'GET_ACTIVE_LOADS_REQUEST';
export const GET_ACTIVE_LOADS_SUCCESS = 'GET_ACTIVE_LOADS_SUCCESS';

export const ITERATE_TO_NEXT_STATE_REQUEST = 'ITERATE_TO_NEXT_STATE_REQUEST';
