export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';

export const FORGOT_PASS_REQUEST = 'FORGOT_PASS_REQUEST';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const CHANGE_PASS_REQUEST = 'CHANGE_PASS_REQUEST';

export const DELETE_ACC_REQUEST = 'DELETE_ACC_REQUEST';

export const GET_USER_INFO_REQUEST = 'GET_USER_INFO_REQUEST';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
