export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';

export const FORGOT_PASS_REQUEST = 'FORGOT_PASS_REQUEST';
