const constants = {
	//routes
	LOGIN_ROUTE: '/auth/login',
	REGISTER_ROUTE: '/auth/register',
	FORGOT_PASS_ROUTE: '/auth/forgot-password',
	PROFILE_ROUTE: '/home/profile',
	TRUCKS_ROUTE: '/home/my-trucks',
	LOADS_ROUTE: '/home/my-loads',
	//images
	LOGO_SRC: '/assets/logo.jpg',
	LOGO_ALT_VALUE: 'company logo',
	USER_PHOTO_SRC: '/assets/user-photo.png',
	USER_PHOTO_ALT_VALUE: 'user',
	MENU_BURGER_SRC: '/assets/icons/menu-burger-icon.png',
	MENU_BURGER_ALT_VALUE: 'menu icon',
	PROFILE_SRC: '/assets/icons/profile-icon.png',
	PROFILE_ALT_VALUE: 'profile icon',
	TRUCKS_SRC: '/assets/icons/truck-icon.png',
	TRUCKS_ALT_VALUE: 'truck icon',
	LOAD_SRC: '/assets/icons/load-icon.png',
	LOAD_ALT_VALUE: 'load icon',
	LOGOUT_SRC: '/assets/icons/logout-icon.png',
	LOGOUT_ALT_VALUE: 'logout icon',
	CHECK_MARK_SRC: '/assets/check-mark.png',
	CHECK_MARK_ALT_VALUE: 'check mark icon',
	ERROR_ICON_SRC: '/assets/icons/error-icon.png',
	ERROR_ICON_ALT_VALUE: 'error icon',
	SPRINTER_SRC: '/assets//icons/sprinter-icon.png',
	SMALL_STRAIGHT_SRC: '/assets/icons/small-straight-icon.png',
	LARGE_STRAIGHT_SRC: '/assets/icons/large-straight-icon.png',
	DOUBLE_TICK_SRC: '/assets/icons/double-tick-icon.png',
	DOUBLE_TICK_ALT_VALUE: 'double tick icon',
	EDIT_ICON_SRC: '/assets/icons/edit-icon.png',
	EDIT_ICON_ALT_VALUE: 'edit icon',
	DELETE_ICON_SRC: '/assets/icons/delete-icon.png',
	DELETE_ICON_ALT_VALUE: 'delete icon',
	DIMENSIONS_ICON_SRC: '/assets/icons/dimensions-icon.png',
	DIMENSIONS_ICON_ALT_VALUE: 'dimensions icon',
	DESTINATION_ICON_SRC: '/assets/icons/destination-icon.png',
	DESTINATION_ICON_ALT_VALUE: 'destination icon',
	BACK_ICON_SRC: '/assets/icons/back-icon.png',
	BACK_ICON_ALT_VALUE: 'back icon',
	CLOSE_ICON_SRC: '/assets/icons/close-icon.png',
	CLOSE_ICON_ALT_VALUE: 'close icon',
	//inputs
	INPUT_TEXT: 'text',
	INPUT_NUMBER: 'number',
	INPUT_NAME: 'name',
	INPUT_NAME_PLACEHOLDER: 'Enter your name',
	INPUT_EMAIL: 'email',
	INPUT_EMAIL_PLACEHOLDER: 'Enter your email',
	INPUT_PASS: 'password',
	INPUT_PASS_PLACEHOLDER: 'Enter your password',
	INPUT_CONFIRM_PASS: 'confirm password',
	INPUT_CONFIRM_PASS_PLACEHOLDER: 'Confirm your password',
	INPUT_NEW_PASS: 'new password',
	INPUT_NEW_PASS_PLACEHOLDER: 'Enter new password',
	INPUT_RADIO: 'radio',
	INPUT_RADIO_NAME: 'role',
	INPUT_LOAD_NAME_PLACEHOLDER: 'Enter load name',
	INPUT_PICKUP_ADDR: 'pickup-address',
	INPUT_PICKUP_ADDR_PLACEHOLDER: 'Enter pick-up address',
	INPUT_DEL_ADDR: 'delivery-address',
	INPUT_DEL_ADDR_PLACEHOLDER: 'Enter delivery address',
	INPUT_PAYLOAD: 'payload',
	INPUT_LENGTH: 'length',
	INPUT_WIDTH: 'width',
	INPUT_HEIGHT: 'height',
	//select
	SELECT_ID_ADD_TRUCK: 'add-truck-select',
	SELECT_ID_EDIT_TRUCK: 'edit-truck-select',
	SPRINTER_TYPE: 'SPRINTER',
	SMALL_STRAIGHT_TYPE: 'SMALL STRAIGHT',
	LARGE_STRAIGHT_TYPE: 'LARGE STRAIGHT',
	SELECT_TRUCK_DEFAULT_VALUE: 'TRUCK TYPE',
	SELECT_TRUCK_OPTIONS: ['SPRINTER', 'SMALL STRAIGHT', 'LARGE STRAIGHT'],
	SELECT_ID_LOAD_STATUS: 'load-status-select',
	LOAD_STATUS_NEW: 'NEW',
	LOAD_STATUS_ASSIGNED: 'ASSIGNED',
	LOAD_STATUS_SHIPPED: 'SHIPPED',
	SELECT_LOAD_DEFAULT_VALUE: 'SORT LOADS',
	SELECT_ALL_LOADS: 'ALL LOADS',
	SELECT_LOAD_OPTIONS: ['ALL LOADS', 'NEW', 'ASSIGNED', 'SHIPPED'],
	//buttons
	BUTTON_TYPE_BUTTON: 'button',
	BUTTON_TYPE_SUBMIT: 'submit',

	BUTTON_TEXT_LOGIN: 'Login',
	BUTTON_TEXT_SIGNUP: 'Sign up',
	BUTTON_TEXT_SEND: 'Send',
	BUTTON_TEXT_DELETE_ACC: 'Delete Account',
	BUTTON_TEXT_CHANGE_PASS: 'Change Password',
	BUTTON_TEXT_LOGOUT: 'Logout',
	BUTTON_TEXT_ADD: 'Add',
	BUTTON_TEXT_ASSIGN: 'Assign',
	BUTTON_TEXT_OK: 'OK',
	BUTTON_TEXT_FINISH_DEL: 'Finish Delivery',
	BUTTON_TEXT_POST: 'POST',
	BUTTON_TEXT_ADD_LOAD: 'ADD NEW LOAD',
	BUTTON_TEXT_UPDATE: 'Update',
	BUTTON_TEXT_CHANGE: 'Change',
	BUTTON_TEXT_CANCEL: 'Cancel',
	BUTTON_TEXT_DELETE: 'Delete',
	//title
	TITLE_PROFILE: 'Profile',
	TITLE_TRUCKS: 'My Trucks',
	TITLE_LOADS: 'My Loads',
	TITLE_LOGOUT: 'Logout',

	BASE_URL: 'http://localhost:8080/api',

	DRIVER_ROLE: 'DRIVER',
	SHIPPER_ROLE: 'SHIPPER',

	TRUCK_STATUS_IS: 'IS',
	TRUCK_STATUS_OL: 'OL',
};

export default constants;
