export const GET_TRUCKS_REQUEST = 'GET_TRUCKS_REQUEST';
export const GET_TRUCKS_SUCCESS = 'GET_TRUCKS_SUCCESS';

export const ADD_TRUCK_REQUEST = 'ADD_TRUCK_REQUEST';
export const ADD_TRUCK_SUCCESS = 'ADD_TRUCK_SUCCESS';
