export const GET_TRUCKS_REQUEST = 'GET_TRUCKS_REQUEST';
export const GET_TRUCKS_SUCCESS = 'GET_TRUCKS_SUCCESS';

export const ADD_TRUCK_REQUEST = 'ADD_TRUCK_REQUEST';
export const EDIT_TRUCK_REQUEST = 'EDIT_TRUCK_REQUEST';

export const DELETE_TRUCK_REQUEST = 'DELETE_TRUCK_REQUEST';
export const DELETE_TRUCK_SUCCESS = 'DELETE_TRUCK_SUCCESS';
